server:
  port: 8080

spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

