spring:
  application:
    name: userapp

eureka:
  client:
    register-with-eureka: true   #注册eureka
    fetch-registry: true    # 获取注册信息
    # 需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8001/eureka